### ISSUE TITLE
Use SpactimeDB for the world database?

### ISSUE THREAD

**Issue by ValorZard** [mas-bandwidth/fps#1]
Hey! Just read your article on how to make a first person shooter with a million players, and I thought it was really interesting that you mentioned that someone show make an open sourcereal time database for games cuz that already exists. It’s called space time db (https://spacetimedb.com/) (https://github.com/ClockworkLabs/SpacetimeDB) I think the general idea is a little different from what you were thinking, but it would be really cool to see if you could integrate it somehow.

**Comment by gafferongames** [comment]
It's nice to see other people have a similar idea around databases, however I have looked at SpacetimeDB and it is not the same thing I have in mind for this system. Best wishes!
